name: Update Credly Badges

on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  update-readme:
    name: Update Readme with Credly Badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: fatum
